// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwKLHNBlCo1bBYFMBSNdtNcdczo7g5Pic',
    appId: '1:751275720761:android:d79ba0685cdfa0c01fcde8',
    messagingSenderId: '751275720761',
    projectId: 'wechat-chat-app',
    storageBucket: 'wechat-chat-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlCmi-SkkYw7Al2yk1bBQQI9kPDevixDs',
    appId: '1:751275720761:ios:2c739b12a44496c31fcde8',
    messagingSenderId: '751275720761',
    projectId: 'wechat-chat-app',
    storageBucket: 'wechat-chat-app.appspot.com',
    androidClientId: '751275720761-761qgkprvh0thihllbcgnn8o6sdpp9n7.apps.googleusercontent.com',
    iosClientId: '751275720761-dmsj41abu3qf6foi2rtpdc0qr0itg8r3.apps.googleusercontent.com',
    iosBundleId: 'com.wechat.chatapp',
  );
}
